/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl.validation

import org.eclipse.xtext.validation.Check
import net.adempiere.tang.dsl.tang.TangPackage
import net.adempiere.tang.dsl.tang.TangType
import net.adempiere.tang.dsl.tang.EntityViewAlias
import net.adempiere.tang.dsl.tang.EntityViewField
import net.adempiere.tang.dsl.tang.Field

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class TangValidator extends AbstractTangValidator {
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkTypeStartsWithCapital(TangType tangType) {
		if (!Character.isUpperCase(tangType.name.charAt(0))) {
			warning('Name should start with a capital', 
					TangPackage.Literals.TANG_ABSTRACT_ELEMENT__NAME,
					INVALID_NAME)
		}
	}

/* 	@Check
	def checkEntityStartsWithCapital(TangEntity tangEntity) {
		if (!Character.isUpperCase(tangEntity.name.charAt(0))) {
			warning('Name should start with a capital', 
					TangPackage.Literals.TANG_ENTITY__NAME,
					INVALID_NAME)
		}
	}
*/
	@Check
	def checkAttributeStartsWithLower(Field tangAttribute) {
		if (!Character.isLowerCase(tangAttribute.name.charAt(0))) {
			warning('Name should start with a lower', 
					TangPackage.Literals.FIELD__NAME,
					INVALID_NAME)
		}
	}

	@Check
	def checkEntityViewAliasStartsWithLower(EntityViewAlias entityViewAlias) {
		if (!Character.isLowerCase(entityViewAlias.name.charAt(0))) {
			warning('Alias should start with a lower', 
					TangPackage.Literals.ENTITY_VIEW_ALIAS__NAME,
					INVALID_NAME)
		}
	}

	@Check
	def checkEntityViewFieldStartsWithLower(EntityViewField entityViewField) {
		if (!Character.isLowerCase(entityViewField.name.charAt(0))) {
			warning('Alias should start with a lower', 
					TangPackage.Literals.ENTITY_VIEW_FIELD__NAME,
					INVALID_NAME)
		}
	}
}
