/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl.tests

import com.google.inject.Inject
import net.adempiere.tang.dsl.tang.TangModule
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(TangInjectorProvider)
class TangParsingTest {
	@Inject
	ParseHelper<TangModule> parseHelper
	
	@Test
	def void loadExampleModel() {
		val result = parseHelper.parse(
		'''
		package net.adempiere.tang.common {
			integer-type IdType	{ java-type="Integer" max-digits=10 allow-null=false }

			entity BaseEntity db-table-name="base" {
				id: IdType db-column-name="id";

				primary-key base_pk {id}
			}
		}
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}


}
