/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class TangStandaloneSetup extends TangStandaloneSetupGenerated {

	def static void doSetup() {
		new TangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
