/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class TangRuntimeModule extends AbstractTangRuntimeModule {
}
