/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class TangWebModule extends AbstractTangWebModule {
}
