/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl.ui.wizard;

import org.eclipse.ui.dialogs.WizardNewProjectCreationPage;

public class TangWizardNewProjectCreationPage extends WizardNewProjectCreationPage {

	public TangWizardNewProjectCreationPage(String pageName) {
		super(pageName);
	}

}
