/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl.ide

import com.google.inject.Guice
import net.adempiere.tang.dsl.TangRuntimeModule
import net.adempiere.tang.dsl.TangStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class TangIdeSetup extends TangStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new TangRuntimeModule, new TangIdeModule))
	}
	
}
