/*
 * generated by Xtext 2.12.0
 */
package net.adempiere.tang.dsl.ui.outline

import net.adempiere.tang.dsl.tang.Field
import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider

/**
 * Customization of the default outline structure.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
class TangOutlineTreeProvider extends DefaultOutlineTreeProvider {

	// @Trifon
	def _isLeaf(Field field) {
		return true;
	}
}
